--let g:go_highlight_build_constraints = 1
--let g:go_highlight_extra_types = 1
--let g:go_highlight_fields = 1
--let g:go_highlight_functions = 1
--let g:go_highlight_methods = 1
--let g:go_highlight_operators = 1
--let g:go_highlight_structs = 1
--let g:go_highlight_types = 1
--"let g:go_auto_sameids = 0
--let g:go_fmt_command = "goimports"
--"let g:go_auto_type_info = 1
--let g:go_addtags_transform = "camelcase"
--let g:go_metalinter_command='golangci-lint'
--let g:go_metalinter_enabled = ['deadcode', 'errcheck', 'gosimple', 'govet', 'staticcheck', 'typecheck', 'unused', 'varcheck', 'bodyclose', 'goconst', 'unconvert', 'gocritic', 'gochecknoinits', 'gofmt']

vim.g.go_highlight_build_constraints = 1
vim.g.go_highlight_extra_types = 1
vim.g.go_highlight_fields = 1
vim.g.go_highlight_functions = 1
vim.g.go_highlight_methods = 1
vim.g.go_highlight_operators = 1
vim.g.go_highlight_structs = 1
vim.g.go_highlight_types = 1
vim.g.go_fmt_command = 'goimports'
vim.g.go_addtags_transform = 'camelcase'
vim.g.go_metalinter_command = 'golangci-lint'
vim.g.go_metalinter_enabled = "['bodyclose', 'goconst', 'unconvert', 'gocritic', 'gochecknoinits', 'gofmt', 'gosec', 'revive']"
--vim.g.go_metalinter_enabled = "['bodyclose', 'goconst', 'unconvert', 'gochecknoinits', 'gofmt', 'gosec', 'revice']"

